config/routes.rb
Rails.application.routes.draw do

  root to: "questions_controller#ask"
  get '/answer', to: "questions_controller#answer"

  get '/ask', to: "questions_controller#ask"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller_controller.rb
class QuestionsControllerController < ApplicationController
  def answer
    question = params[:question]
    if question != "Going to work now!"
      if question.include? "?"
        if question == "what time is it?"
          @answer = "It is #{Time.now}"
        else
          @answer = "Another silly question!"
        end
      else
        @answer = "Whatever, I don't really care..."
      end
    else
      @answer = "Yeah, about time!"
    end
  end

  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_controller_helper.rb
module QuestionsControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"

  </head>

  <body>
    <div class="container">
      <h1 class="text-center">Your personal coach</h1>
      <hr>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions_controller/answer.html.erb
<div class="container text-center">
  <h3><%=params[:question]%></h3>
  <p>-->You asked</p>
  <h3><%=@answer%></h3>
  <p>-->Your coach said</p>
  <h3 class="btn btn-info"><%= link_to "Another question?", ask_path %><h3>
</div>

app/views/questions_controller/ask.html.erb
<form action="/answer" class="form-group text-center">
  <label for="question" class="text-success">Speak to your coach</label>
  <input type="text" id="question" name="question" placeholder="what time is it?" class="form-inline input-lg">
  <input type="submit" value="Go on!" class="btn-lg btn-primary-lg">
</form>